---
- hosts: servers
  gather_facts: true
  vars_prompt:
    - name: domain
      prompt: "Domain"
      private: false

    - name: php_version
      prompt: "PHP Version"
      private: false

    - name: vault_url
      prompt: "Vault URL"
      private: false

    - name: vault_access_token
      prompt: "Vault Token"
      private: false

    - name: git_repository
      prompt: "Git repository SSH URL"
      private: false

    - name: git_branch
      prompt: "Git repository branch"
      private: false
      default: "{{ domain }}"

    - name: deploy_namespace
      prompt: "Deploy namespace"
      private: false
      default: "{{ domain | default('main') }}"

  pre_tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 0

    - name: Install acl, git, nginx
      become: true
      apt:
        state: present
        name:
          - acl
          - git
          - nginx

  tasks:
    - name: Install certbot
      include_tasks: tasks/install-certbot.yml

    - name: Install PHP
      include_tasks: tasks/install-php.yml

    - name: Install composer
      include_tasks: tasks/install-composer.yml

    - name: Setup .env
      include_tasks: tasks/setup-env.yml

    - name: Install & Setup MySQL database
      include_tasks: tasks/install-mysql-database.yml
      when: DB_CONNECTION == "mysql"

    - name: Install & Setup PostgreSQL database
      include_tasks: tasks/install-postgres-database.yml
      when: DB_CONNECTION == "pgsql"

    - name: Setup git repository
      include_tasks: tasks/setup-git-repository.yml

    - name: Deploy git repository
      include_tasks: tasks/deploy-git-repository.yml

    - name: Setup nginx
      include_tasks: tasks/setup-nginx.yml

    - name: Setup SSL
      include_tasks: tasks/setup-ssl.yml
