---
- hosts: servers
  gather_facts: true
  vars_prompt:
    - name: username
      prompt: "New mysql Username"
      private: false

    - name: password
      prompt: "New mysql Password"
      private: false

    - name: database
      prompt: "New mysql Database"
      private: false

  tasks:
    - name: Install nginx
      include_tasks: tasks/install-nginx.yml

    - name: Install PHP 8.1
      include_tasks: tasks/install-php.yml

    - name: Install mariadb
      include_tasks: tasks/install-mariadb.yml

    - name: Setup mariadb database
      include_tasks: tasks/setup-mariadb-database.yml

    - name: Setup mariadb user
      include_tasks: tasks/setup-mariadb-user.yml
