---
- hosts: servers
  gather_facts: true
  vars_prompt:
    - name: domain
      prompt: "Domain"
      private: false

    - name: php_version
      prompt: "PHP Version"
      private: false

    - name: mysql_username
      prompt: "New mysql Username"
      private: false

    - name: mysql_password
      prompt: "New mysql Password"
      private: false

    - name: mysql_database
      prompt: "New mysql Database"
      private: false

    - name: github_repository
      prompt: "Github Repository SSH URL"
      private: false

  pre_tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400

    - name: Install acl, git, nginx, mariadb-server, python3-mysqldb, certbot
      become: true
      apt:
        state: present
        name:
          - acl
          - git
          - nginx
          - mariadb-server
          - python3-mysqldb
          - certbot

  tasks:
    - name: Install PHP
      include_tasks: tasks/install-php.yml

    - name: Install composer
      include_tasks: tasks/install-composer.yml

    - name: Setup mariadb database
      include_tasks: tasks/setup-mariadb-database.yml

    - name: Setup mariadb user
      include_tasks: tasks/setup-mariadb-user.yml

    - name: Setup github repository
      include_tasks: tasks/setup-github-repository.yml

    - name: Deploy github repository
      include_tasks: tasks/deploy-github-repository.yml
