---
- hosts: servers
  gather_facts: true
  vars_prompt:
    - name: domain
      prompt: "Domain"
      private: false

    - name: php_version
      prompt: "PHP Version"
      private: false

    - name: vault_url
      prompt: "Vault URL"
      private: false

    - name: vault_access_token
      prompt: "Vault Token"
      private: false

    - name: git_repository
      prompt: "Git repository SSH URL"
      private: false

    - name: git_branch
      prompt: "Git repository branch"
      private: false

  pre_tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400

    - name: Install acl, git, nginx, mysql-server, python3-mysqldb, certbot
      become: true
      apt:
        state: present
        name:
          - acl
          - git
          - nginx
          - mysql-server
          - python3-mysqldb
          - certbot

  tasks:
    - name: Install PHP
      include_tasks: tasks/install-php.yml

    - name: Install composer
      include_tasks: tasks/install-composer.yml

    - name: Setup .env
      include_tasks: tasks/setup-env.yml

    - name: Setup mysql database
      include_tasks: tasks/setup-mysql-database.yml

    - name: Setup mysql user
      include_tasks: tasks/setup-mysql-user.yml

    - name: Setup git repository
      include_tasks: tasks/setup-git-repository.yml

    - name: Deploy git repository
      include_tasks: tasks/deploy-git-repository.yml

    - name: Setup nginx
      include_tasks: tasks/setup-nginx.yml

    - name: Setup SSL
      include_tasks: tasks/setup-ssl.yml
