---
- name: "Install node.js {{ node_version }}"
  shell: source ~/.nvm/nvm.sh && nvm install {{ node_version }}
  args:
    executable: /bin/bash
    creates: "~/.nvm/versions/node/{{ node_version }}"
