---
- name: Install deployer
  shell: |
    cd ~/{{ git_repository|splitext|first|split(':')|last }}
    composer require --dev deployer/deployer

- name: Copy deploy.yml
  template:
    src: templates/deploy.template.yml
    dest: "~/{{ git_repository|splitext|first|split(':')|last }}/deploy.yml"
    force: false

- name: Create /var/www/{{ domain }} directory
  become: true
  file:
    path: "/var/www/{{ domain }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory
    mode: '0755'

- name: Deploy application
  shell: |
    cd ~/{{ git_repository|splitext|first|split(':')|last }}
    vendor/bin/dep deploy
