---
- name: Install deployer
  shell: |
    cd ~/{{ git_repository|splitext|first|split(':')|last }}
    composer require --dev deployer/deployer

- name: Copy deploy.yaml
  template:
    src: templates/deploy.template.yaml
    dest: "~/{{ git_repository|splitext|first|split(':')|last }}/deploy.yaml"
    force: false

- name: Add node and npm symlinks for non-login shell
  become: true
  shell: |
    ln -s {{ ansible_env.HOME }}/.nvm/versions/node/{{ node_version }}/bin/node /usr/bin/
    ln -s {{ ansible_env.HOME }}/.nvm/versions/node/{{ node_version }}/bin/npm /usr/bin/

- name: Deploy application
  shell: |
    cd ~/{{ git_repository|splitext|first|split(':')|last }}
    vendor/bin/dep deploy {{ deploy_namespace }} -o hostname=localhost

- name: Remove node and npm symlinks
  become: true
  shell: |
    rm /usr/bin/node
    rm /usr/bin/npm
