---
- name: Install deployer
  shell: |
    cd ~/{{ git_repository|splitext|first|split(':')|last }}
    composer require --dev deployer/deployer

- name: Check if 'deploy.yml' exists in the project
  stat:
    path: "~/{{ git_repository|splitext|first|split(':')|last }}/deploy.yaml"
  register: deploy_yml_file_check

- name: Copy deploy.yml
  template:
    src: templates/deploy.template.yml
    dest: "~/{{ git_repository|splitext|first|split(':')|last }}/deploy.yaml"
    force: false
  when: deploy_yml_file_check.stat.exists == False

- name: Add node and npm symlinks for non-login shell
  become: true
  shell: |
    ln -s ~/.nvm/versions/node/{{ node_version }}/bin/node /usr/bin/
    ln -s ~/.nvm/versions/node/{{ node_version }}/bin/npm /usr/bin/

- name: Deploy application
  shell: |
    cd ~/{{ git_repository|splitext|first|split(':')|last }}
    vendor/bin/dep deploy {{ deploy_namespace }} -o hostname=localhost

- name: Remove node and npm symlinks
  become: true
  shell: |
    rm /usr/bin/node
    rm /usr/bin/npm
