---
- name: Install deployer
  shell: |
    cd ~/{{ git_repository|splitext|first|split(':')|last }}
    composer require --dev deployer/deployer

- name: Copy deploy.yml
  template:
    src: templates/deploy.template.yml
    dest: "~/{{ git_repository|splitext|first|split(':')|last }}/deploy.yml"
    force: false

- name: Deploy application
  shell: |
    cd ~/{{ git_repository|splitext|first|split(':')|last }}
    vendor/bin/dep deploy {{ git_branch }} -vvv
