---
- name: Create deployer directory
  file:
    path: "~/{{ git_repository|splitext|first|split(':')|last }}"
    state: directory

- name: Install deployer
  shell: |
    cd ~/{{ git_repository|splitext|first|split(':')|last }}
    composer require --dev deployer/deployer

- name: Copy deploy.php
  template:
    src: templates/deploy.template.php
    dest: "~/{{ git_repository|splitext|first|split(':')|last }}/deploy.php"

- name: Create /var/www/{{ domain }} directory
  become: true
  file:
    path: "/var/www/{{ domain }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory
    mode: '0755'

- name: Deploy application
  shell: |
    cd ~/{{ git_repository|splitext|first|split(':')|last }}
    vendor/bin/dep deploy
