---
- name: Add ppa:ondrej/php repository
  become: true
  apt_repository:
    repo: ppa:ondrej/php
    state: present

- name: Install PHP
  become: true
  apt:
    state: present
    name:
      - php{{ php_version }}-fpm
      - php{{ php_version }}-common
      - php{{ php_version }}-mbstring
      - php{{ php_version }}-gd
      - php{{ php_version }}-xml
      - php{{ php_version }}-mysql
      - php{{ php_version }}-cli
      - php{{ php_version }}-zip
      - php{{ php_version }}-curl
