---
- name: Setup github repository
  git:
    repo: "{{ github_repository }}"
    dest: "{{ ansible_env.HOME }}/{{ github_repository|splitext|first|split(':')|last }}"
    version: "main"
    force: yes
    accept_hostkey: yes
